# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user_a = User.create( username: "bob", password: "password")
user_b = User.create( username: "jane", password: "password")
user_c = User.create( username: "jill", password: "password")

al=PropTaxRate.create( state: 'AL', tax_rate: 0.0042 )
ak=PropTaxRate.create(  state: 'AK', tax_rate: 0.0118 )
az=PropTaxRate.create(  state: 'AZ', tax_rate: 0.0069 )
ar=PropTaxRate.create(  state: 'AR', tax_rate: 0.0063 )
ca=PropTaxRate.create(  state: 'CA', tax_rate: 0.0076 )
co=PropTaxRate.create(  state: 'CO', tax_rate: 0.0053 )
ct=PropTaxRate.create(  state: 'CT', tax_rate: 0.0211 )
de=PropTaxRate.create(  state: 'DE', tax_rate: 0.0056 )
fl=PropTaxRate.create(  state: 'FL', tax_rate: 0.0093 )
ga=PropTaxRate.create(  state: 'GA', tax_rate: 0.0091 )
hi=PropTaxRate.create(  state: 'HI', tax_rate: 0.0027 )
id=PropTaxRate.create(  state: 'ID', tax_rate: 0.0072 )
il=PropTaxRate.create(  state: 'IL', tax_rate: 0.023 )
indiana=PropTaxRate.create(  state: 'IN', tax_rate: 0.0086 )
ia=PropTaxRate.create(  state: 'IA', tax_rate: 0.0156 )
ks=PropTaxRate.create(  state: 'KS', tax_rate: 0.0141 )
ky=PropTaxRate.create(  state: 'KY', tax_rate: 0.0086 )
la=PropTaxRate.create(  state: 'LA', tax_rate: 0.0053 )
me=PropTaxRate.create(  state: 'ME', tax_rate: 0.0136 )
md=PropTaxRate.create(  state: 'MD', tax_rate: 0.0109 )
ma=PropTaxRate.create(  state: 'MA', tax_rate: 0.0123 )
mi=PropTaxRate.create(  state: 'MI', tax_rate: 0.0158 )
mn=PropTaxRate.create(  state: 'MN', tax_rate: 0.0113 )
ms=PropTaxRate.create(  state: 'MS', tax_rate: 0.0081 )
mo=PropTaxRate.create(  state: 'MO', tax_rate: 0.0097 )
mt=PropTaxRate.create(  state: 'MT', tax_rate: 0.0084 )
ne=PropTaxRate.create(  state: 'NE', tax_rate: 0.0177 )
nv=PropTaxRate.create(  state: 'NV', tax_rate: 0.0064 )
nh=PropTaxRate.create(  state: 'NH', tax_rate: 0.022 )
nj=PropTaxRate.create(  state: 'NJ', tax_rate: 0.0247 )
nm=PropTaxRate.create(  state: 'NM', tax_rate: 0.0079 )
ny=PropTaxRate.create(  state: 'NY', tax_rate: 0.0171 )
nc=PropTaxRate.create(  state: 'NC', tax_rate: 0.0085 )
nd=PropTaxRate.create(  state: 'ND', tax_rate: 0.0099 )
oh=PropTaxRate.create(  state: 'OH', tax_rate: 0.0158 )
ok=PropTaxRate.create(  state: 'OK', tax_rate: 0.009 )
oregon=PropTaxRate.create(  state: 'OR', tax_rate: 0.0101 )
pa=PropTaxRate.create(  state: 'PA', tax_rate: 0.0159 )
ri=PropTaxRate.create(  state: 'RI', tax_rate: 0.0166 )
sc=PropTaxRate.create(  state: 'SC', tax_rate: 0.0057 )
sd=PropTaxRate.create(  state: 'SD', tax_rate: 0.0132 )
tn=PropTaxRate.create(  state: 'TN', tax_rate: 0.0073 )
tx=PropTaxRate.create(  state: 'TX', tax_rate: 0.0181 )
ut=PropTaxRate.create(  state: 'UT', tax_rate: 0.0064 )
vt=PropTaxRate.create(  state: 'VT', tax_rate: 0.0188 )
va=PropTaxRate.create(  state: 'VA', tax_rate: 0.0081 )
wa=PropTaxRate.create(  state: 'WA', tax_rate: 0.0101 )
wv=PropTaxRate.create(  state: 'WV', tax_rate: 0.0059 )
wi=PropTaxRate.create(  state: 'WI', tax_rate: 0.0191 )
wy=PropTaxRate.create(  state: 'WY', tax_rate: 0.0061 )

gr_30=MortgInterestRate.create( credit_score: 'great', loan_length_yrs: 30, interest_rate:  0.02875)
gr_20=MortgInterestRate.create( credit_score: 'great', loan_length_yrs: 20, interest_rate:  0.02875)
gr_15=MortgInterestRate.create( credit_score: 'great', loan_length_yrs: 15, interest_rate:  0.02375)
gr_10=MortgInterestRate.create( credit_score: 'great', loan_length_yrs: 10, interest_rate:  0.02375)
go_30=MortgInterestRate.create( credit_score: 'good', loan_length_yrs: 30, interest_rate:  0.03075)
go_20=MortgInterestRate.create( credit_score: 'good', loan_length_yrs: 20, interest_rate:  0.03075)
go_15=MortgInterestRate.create( credit_score: 'good', loan_length_yrs: 15, interest_rate:  0.02575)
go_10=MortgInterestRate.create( credit_score: 'good', loan_length_yrs: 10, interest_rate:  0.02575)
fa_30=MortgInterestRate.create( credit_score: 'fair', loan_length_yrs: 30, interest_rate:  0.03275)
fa_20=MortgInterestRate.create( credit_score: 'fair', loan_length_yrs: 20, interest_rate:  0.03275)
fa_15=MortgInterestRate.create( credit_score: 'fair', loan_length_yrs: 15, interest_rate:  0.02775)
fa_10=MortgInterestRate.create( credit_score: 'fair', loan_length_yrs: 10, interest_rate:  0.02775)
po_30=MortgInterestRate.create( credit_score: 'poor', loan_length_yrs: 30, interest_rate:  0.03475)
po_20=MortgInterestRate.create( credit_score: 'poor', loan_length_yrs: 20, interest_rate:  0.03475)
po_15=MortgInterestRate.create( credit_score: 'poor', loan_length_yrs: 15, interest_rate:  0.02975)
po_10=MortgInterestRate.create( credit_score: 'poor', loan_length_yrs: 10, interest_rate:  0.02975)

scen_a = Scenario.create(net_income: 100000, income_after_tax: 70000, monthly_debt: 500, credit_score: 'good',
     downpayment: 20000, state: 'TX', city: 'Austin', prop_tax_rate_id: tx.id, mortg_interest_rate_id: gr_15.id, user_id: user_a.id)
scen_b = Scenario.create(net_income: 75000, income_after_tax: 50000, monthly_debt: 200, credit_score: 'poor',
     downpayment: 10000, state: 'TX', city: 'Dallas', prop_tax_rate_id: tx.id, mortg_interest_rate_id: gr_20.id, user_id: user_b.id)
scen_c = Scenario.create(net_income: 85000, income_after_tax: 60000, monthly_debt: 350, credit_score: 'fair',
     downpayment: 15000, state: 'TX', city: 'Houston', prop_tax_rate_id: tx.id, mortg_interest_rate_id: gr_30.id, user_id: user_c.id)
